import type { Metadata } from "next";
import "./globals.css";
import Topbar from "./ui/header/topnav";
import Sidebar from "./ui/header/sidenav";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children, }: { children: React.ReactNode; }) {
  return (
    <html lang="en">
      <body className="bg-[#06253A]">
       
        <div className="hidden md:block">  {/* Topbar só em telas ≥ md */}
          <Topbar />
        </div>

        
        <div className="block md:hidden"> {/* Sidebar só em telas < md */}
          <Sidebar />
        </div>

        {children}
      </body>
    </html>
  );
}
