import type { Metadata } from "next";
import "./globals.css";
import Topbar from "./components/main_page/header/topnav";
import Sidebar from "./components/main_page/header/sidenav";
import Hero from "./components/main_page/background/BackgroundRotator";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children, }: { children: React.ReactNode; }) {
  return (
    <html lang="en">
      <body>

        <div className="hidden md:block">  {/* Topbar só em telas ≥ md */}
          <Topbar />
        </div>

        <div className="block md:hidden"> {/* Sidebar só em telas < md */}
          <Sidebar />
        </div>

        {children}

      </body>
    </html>
  );
}
